const mongoose = require("mongoose")

const ttSchema = new mongoose.Schema({
    batch: String,
    lecture00: String,
    lecture01: String,
    lecture02: String,
    lecture03: String,
    lecture04: String,
    lecture05: String,
    lecture06: String,
    lecture07: String,
    lecture08: String,
    lecture09: String,
    lecture10: String,
    lecture11: String,
    lecture12: String,
    lecture13: String,
    lecture14: String,
    lecture15: String,
    lecture16: String,
    lecture17: String,
    lecture18: String,
    lecture19: String,
    lecture20: String,
    lecture21: String,
    lecture22: String,
    lecture23: String,
    lecture24: String,
    lecture25: String,
    lecture26: String,
    lecture27: String,
    lecture28: String,
    lecture29: String,
    lecture30: String,
    lecture31: String,
    lecture32: String,
    lecture33: String,
    lecture34: String,
    lecture35: String,
    lecture36: String,
    lecture37: String,
    lecture38: String,
    lecture39: String,
    lecture40: String,
    lecture41: String,
    lecture42: String,
    lecture43: String,
    lecture44: String,
    lecture45: String,
    lecture46: String,
    lecture47: String,
    lecture48: String,
    lecture49: String,
})

module.exports = new mongoose.model("TimeTable", ttSchema)